# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addlayer_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddLayer(object):
    def setupUi(self, AddLayer):
        AddLayer.setObjectName("AddLayer")
        AddLayer.resize(520, 474)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddLayer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vector_radioButton = QtWidgets.QRadioButton(AddLayer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vector_radioButton.setFont(font)
        self.vector_radioButton.setChecked(True)
        self.vector_radioButton.setObjectName("vector_radioButton")
        self.verticalLayout.addWidget(self.vector_radioButton)
        self.vector_groupBox = QtWidgets.QGroupBox(AddLayer)
        self.vector_groupBox.setEnabled(True)
        self.vector_groupBox.setTitle("")
        self.vector_groupBox.setObjectName("vector_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.vector_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vector_name_label = QtWidgets.QLabel(self.vector_groupBox)
        self.vector_name_label.setObjectName("vector_name_label")
        self.gridLayout_3.addWidget(self.vector_name_label, 0, 0, 1, 1)
        self.vector_file_label = QtWidgets.QLabel(self.vector_groupBox)
        self.vector_file_label.setObjectName("vector_file_label")
        self.gridLayout_3.addWidget(self.vector_file_label, 1, 0, 1, 1)
        self.vector_file_lineEdit = QtWidgets.QLineEdit(self.vector_groupBox)
        self.vector_file_lineEdit.setObjectName("vector_file_lineEdit")
        self.gridLayout_3.addWidget(self.vector_file_lineEdit, 1, 1, 1, 1)
        self.vector_loadfile_pushButton = QtWidgets.QPushButton(self.vector_groupBox)
        self.vector_loadfile_pushButton.setObjectName("vector_loadfile_pushButton")
        self.gridLayout_3.addWidget(self.vector_loadfile_pushButton, 1, 2, 1, 1)
        self.vector_name_lineEdit = QtWidgets.QLineEdit(self.vector_groupBox)
        self.vector_name_lineEdit.setObjectName("vector_name_lineEdit")
        self.gridLayout_3.addWidget(self.vector_name_lineEdit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.vector_groupBox)
        self.raster_radioButton = QtWidgets.QRadioButton(AddLayer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.raster_radioButton.setFont(font)
        self.raster_radioButton.setObjectName("raster_radioButton")
        self.verticalLayout.addWidget(self.raster_radioButton)
        self.raster_groupBox = QtWidgets.QGroupBox(AddLayer)
        self.raster_groupBox.setEnabled(False)
        font = QtGui.QFont()
        font.setKerning(True)
        self.raster_groupBox.setFont(font)
        self.raster_groupBox.setTitle("")
        self.raster_groupBox.setObjectName("raster_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.raster_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.raster_file_label = QtWidgets.QLabel(self.raster_groupBox)
        self.raster_file_label.setObjectName("raster_file_label")
        self.gridLayout_4.addWidget(self.raster_file_label, 1, 0, 1, 1)
        self.raster_name_label = QtWidgets.QLabel(self.raster_groupBox)
        self.raster_name_label.setObjectName("raster_name_label")
        self.gridLayout_4.addWidget(self.raster_name_label, 0, 0, 1, 1)
        self.raster_name_lineEdit = QtWidgets.QLineEdit(self.raster_groupBox)
        self.raster_name_lineEdit.setObjectName("raster_name_lineEdit")
        self.gridLayout_4.addWidget(self.raster_name_lineEdit, 0, 1, 1, 1)
        self.raster_file_lineEdit = QtWidgets.QLineEdit(self.raster_groupBox)
        self.raster_file_lineEdit.setObjectName("raster_file_lineEdit")
        self.gridLayout_4.addWidget(self.raster_file_lineEdit, 1, 1, 1, 1)
        self.raster_loadfile_pushButton = QtWidgets.QPushButton(self.raster_groupBox)
        self.raster_loadfile_pushButton.setObjectName("raster_loadfile_pushButton")
        self.gridLayout_4.addWidget(self.raster_loadfile_pushButton, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.raster_groupBox)
        self.tiledwebmap_radioButton = QtWidgets.QRadioButton(AddLayer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tiledwebmap_radioButton.setFont(font)
        self.tiledwebmap_radioButton.setChecked(False)
        self.tiledwebmap_radioButton.setObjectName("tiledwebmap_radioButton")
        self.verticalLayout.addWidget(self.tiledwebmap_radioButton)
        self.mGroupBox = QtWidgets.QGroupBox(AddLayer)
        self.mGroupBox.setEnabled(False)
        self.mGroupBox.setTitle("")
        self.mGroupBox.setObjectName("mGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mCheckBoxZMax_2 = QtWidgets.QCheckBox(self.mGroupBox)
        self.mCheckBoxZMax_2.setChecked(True)
        self.mCheckBoxZMax_2.setObjectName("mCheckBoxZMax_2")
        self.gridLayout_2.addWidget(self.mCheckBoxZMax_2, 5, 0, 1, 2)
        self.mEditName_2 = QtWidgets.QLineEdit(self.mGroupBox)
        self.mEditName_2.setObjectName("mEditName_2")
        self.gridLayout_2.addWidget(self.mEditName_2, 0, 2, 1, 1)
        self.mSpinZMax_2 = QtWidgets.QSpinBox(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mSpinZMax_2.sizePolicy().hasHeightForWidth())
        self.mSpinZMax_2.setSizePolicy(sizePolicy)
        self.mSpinZMax_2.setMaximum(19)
        self.mSpinZMax_2.setProperty("value", 18)
        self.mSpinZMax_2.setObjectName("mSpinZMax_2")
        self.gridLayout_2.addWidget(self.mSpinZMax_2, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 2, 1, 1)
        self.url_twm_label = QtWidgets.QLabel(self.mGroupBox)
        self.url_twm_label.setObjectName("url_twm_label")
        self.gridLayout_2.addWidget(self.url_twm_label, 1, 0, 1, 1)
        self.name_twm_label = QtWidgets.QLabel(self.mGroupBox)
        self.name_twm_label.setObjectName("name_twm_label")
        self.gridLayout_2.addWidget(self.name_twm_label, 0, 0, 1, 2)
        self.url_comboBox = QtWidgets.QComboBox(self.mGroupBox)
        self.url_comboBox.setObjectName("url_comboBox")
        self.url_comboBox.addItem("")
        self.url_comboBox.addItem("")
        self.url_comboBox.addItem("")
        self.url_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.url_comboBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.mGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddLayer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddLayer)
        self.buttonBox.rejected.connect(AddLayer.reject)
        self.vector_radioButton.toggled['bool'].connect(self.vector_groupBox.setEnabled)
        self.raster_radioButton.toggled['bool'].connect(self.raster_groupBox.setEnabled)
        self.tiledwebmap_radioButton.toggled['bool'].connect(self.mGroupBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AddLayer)

    def retranslateUi(self, AddLayer):
        _translate = QtCore.QCoreApplication.translate
        AddLayer.setWindowTitle(_translate("AddLayer", "Dialog"))
        self.vector_radioButton.setText(_translate("AddLayer", "Vector layer from file"))
        self.vector_name_label.setText(_translate("AddLayer", "Name:"))
        self.vector_file_label.setText(_translate("AddLayer", "File:"))
        self.vector_loadfile_pushButton.setText(_translate("AddLayer", "..."))
        self.raster_radioButton.setText(_translate("AddLayer", "Raster layer from file"))
        self.raster_file_label.setText(_translate("AddLayer", "File:"))
        self.raster_name_label.setText(_translate("AddLayer", "Name:"))
        self.raster_loadfile_pushButton.setText(_translate("AddLayer", "..."))
        self.tiledwebmap_radioButton.setText(_translate("AddLayer", "Tiled Web Map Layer"))
        self.mCheckBoxZMax_2.setText(_translate("AddLayer", "Max. Zoom Level"))
        self.mEditName_2.setToolTip(_translate("AddLayer", "Name of the new connection"))
        self.url_twm_label.setText(_translate("AddLayer", "URL"))
        self.name_twm_label.setText(_translate("AddLayer", "Name"))
        self.url_comboBox.setItemText(0, _translate("AddLayer", "Google Hybrid"))
        self.url_comboBox.setItemText(1, _translate("AddLayer", "Google Map"))
        self.url_comboBox.setItemText(2, _translate("AddLayer", "Google Satelite"))
        self.url_comboBox.setItemText(3, _translate("AddLayer", "OpenStreetMap"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddLayer = QtWidgets.QDialog()
    ui = Ui_AddLayer()
    ui.setupUi(AddLayer)
    AddLayer.show()
    sys.exit(app.exec_())

