# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_auvprocesses.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AUVProcessesWidget(object):
    def setupUi(self, AUVProcessesWidget):
        AUVProcessesWidget.setObjectName("AUVProcessesWidget")
        AUVProcessesWidget.resize(675, 45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AUVProcessesWidget.sizePolicy().hasHeightForWidth())
        AUVProcessesWidget.setSizePolicy(sizePolicy)
        AUVProcessesWidget.setMinimumSize(QtCore.QSize(675, 45))
        self.horizontalLayout = QtWidgets.QHBoxLayout(AUVProcessesWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connection_indicator = QtWidgets.QLabel(AUVProcessesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_indicator.sizePolicy().hasHeightForWidth())
        self.connection_indicator.setSizePolicy(sizePolicy)
        self.connection_indicator.setMinimumSize(QtCore.QSize(12, 12))
        self.connection_indicator.setMaximumSize(QtCore.QSize(12, 12))
        self.connection_indicator.setText("")
        self.connection_indicator.setPixmap(QtGui.QPixmap(":/resources/red_led.svg"))
        self.connection_indicator.setScaledContents(True)
        self.connection_indicator.setObjectName("connection_indicator")
        self.horizontalLayout.addWidget(self.connection_indicator)
        self.connection_label = QtWidgets.QLabel(AUVProcessesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_label.sizePolicy().hasHeightForWidth())
        self.connection_label.setSizePolicy(sizePolicy)
        self.connection_label.setMaximumSize(QtCore.QSize(55, 27))
        self.connection_label.setText("")
        self.connection_label.setObjectName("connection_label")
        self.horizontalLayout.addWidget(self.connection_label)
        self.cola2_indicator = QtWidgets.QLabel(AUVProcessesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cola2_indicator.sizePolicy().hasHeightForWidth())
        self.cola2_indicator.setSizePolicy(sizePolicy)
        self.cola2_indicator.setMinimumSize(QtCore.QSize(12, 12))
        self.cola2_indicator.setMaximumSize(QtCore.QSize(12, 12))
        self.cola2_indicator.setText("")
        self.cola2_indicator.setPixmap(QtGui.QPixmap(":/resources/red_led.svg"))
        self.cola2_indicator.setScaledContents(True)
        self.cola2_indicator.setObjectName("cola2_indicator")
        self.horizontalLayout.addWidget(self.cola2_indicator)
        self.cola2_label = QtWidgets.QLabel(AUVProcessesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cola2_label.sizePolicy().hasHeightForWidth())
        self.cola2_label.setSizePolicy(sizePolicy)
        self.cola2_label.setMaximumSize(QtCore.QSize(55, 27))
        self.cola2_label.setText("")
        self.cola2_label.setObjectName("cola2_label")
        self.horizontalLayout.addWidget(self.cola2_label)
        self.startprocess_combo = QtWidgets.QComboBox(AUVProcessesWidget)
        self.startprocess_combo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startprocess_combo.sizePolicy().hasHeightForWidth())
        self.startprocess_combo.setSizePolicy(sizePolicy)
        self.startprocess_combo.setProperty("currentText", "")
        self.startprocess_combo.setObjectName("startprocess_combo")
        self.horizontalLayout.addWidget(self.startprocess_combo)
        self.send_button = QtWidgets.QPushButton(AUVProcessesWidget)
        self.send_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_button.sizePolicy().hasHeightForWidth())
        self.send_button.setSizePolicy(sizePolicy)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.terminateprocess_combo = QtWidgets.QComboBox(AUVProcessesWidget)
        self.terminateprocess_combo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminateprocess_combo.sizePolicy().hasHeightForWidth())
        self.terminateprocess_combo.setSizePolicy(sizePolicy)
        self.terminateprocess_combo.setObjectName("terminateprocess_combo")
        self.horizontalLayout.addWidget(self.terminateprocess_combo)
        self.terminate_button = QtWidgets.QPushButton(AUVProcessesWidget)
        self.terminate_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminate_button.sizePolicy().hasHeightForWidth())
        self.terminate_button.setSizePolicy(sizePolicy)
        self.terminate_button.setObjectName("terminate_button")
        self.horizontalLayout.addWidget(self.terminate_button)

        self.retranslateUi(AUVProcessesWidget)
        self.startprocess_combo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AUVProcessesWidget)

    def retranslateUi(self, AUVProcessesWidget):
        _translate = QtCore.QCoreApplication.translate
        AUVProcessesWidget.setWindowTitle(_translate("AUVProcessesWidget", "AUV Connection"))
        self.send_button.setText(_translate("AUVProcessesWidget", "Send"))
        self.terminate_button.setText(_translate("AUVProcessesWidget", "Terminate"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AUVProcessesWidget = QtWidgets.QWidget()
    ui = Ui_AUVProcessesWidget()
    ui.setupUi(AUVProcessesWidget)
    AUVProcessesWidget.show()
    sys.exit(app.exec_())

