# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_coordinateconverterwidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CoordinateConverterDialog(object):
    def setupUi(self, CoordinateConverterDialog):
        CoordinateConverterDialog.setObjectName("CoordinateConverterDialog")
        CoordinateConverterDialog.resize(550, 333)
        self.gridLayout_2 = QtWidgets.QGridLayout(CoordinateConverterDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.latitudeLabel_dms = QtWidgets.QLabel(CoordinateConverterDialog)
        self.latitudeLabel_dms.setObjectName("latitudeLabel_dms")
        self.gridLayout_2.addWidget(self.latitudeLabel_dms, 7, 0, 1, 1)
        self.longitudelabel_dms = QtWidgets.QLabel(CoordinateConverterDialog)
        self.longitudelabel_dms.setObjectName("longitudelabel_dms")
        self.gridLayout_2.addWidget(self.longitudelabel_dms, 8, 0, 1, 1)
        self.latitudeLabel_dm = QtWidgets.QLabel(CoordinateConverterDialog)
        self.latitudeLabel_dm.setObjectName("latitudeLabel_dm")
        self.gridLayout_2.addWidget(self.latitudeLabel_dm, 4, 0, 1, 1)
        self.longitudelabel_dm = QtWidgets.QLabel(CoordinateConverterDialog)
        self.longitudelabel_dm.setObjectName("longitudelabel_dm")
        self.gridLayout_2.addWidget(self.longitudelabel_dm, 5, 0, 1, 1)
        self.lat_dms_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lat_dms_horizontalLayout.setObjectName("lat_dms_horizontalLayout")
        self.gridLayout_2.addLayout(self.lat_dms_horizontalLayout, 7, 3, 1, 1)
        self.latitudelabel_d = QtWidgets.QLabel(CoordinateConverterDialog)
        self.latitudelabel_d.setObjectName("latitudelabel_d")
        self.gridLayout_2.addWidget(self.latitudelabel_d, 1, 0, 1, 1)
        self.convert_pushButton = QtWidgets.QPushButton(CoordinateConverterDialog)
        self.convert_pushButton.setObjectName("convert_pushButton")
        self.gridLayout_2.addWidget(self.convert_pushButton, 10, 0, 1, 7)
        self.lon_dm_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lon_dm_horizontalLayout.setObjectName("lon_dm_horizontalLayout")
        self.gridLayout_2.addLayout(self.lon_dm_horizontalLayout, 5, 3, 1, 1)
        self.longitudeLabel_d = QtWidgets.QLabel(CoordinateConverterDialog)
        self.longitudeLabel_d.setObjectName("longitudeLabel_d")
        self.gridLayout_2.addWidget(self.longitudeLabel_d, 2, 0, 1, 1)
        self.copyClipboard_pushButton_3 = QtWidgets.QPushButton(CoordinateConverterDialog)
        self.copyClipboard_pushButton_3.setText("")
        self.copyClipboard_pushButton_3.setObjectName("copyClipboard_pushButton_3")
        self.gridLayout_2.addWidget(self.copyClipboard_pushButton_3, 7, 6, 2, 1)
        self.lon_dms_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lon_dms_horizontalLayout.setObjectName("lon_dms_horizontalLayout")
        self.gridLayout_2.addLayout(self.lon_dms_horizontalLayout, 8, 3, 1, 1)
        self.line = QtWidgets.QFrame(CoordinateConverterDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 9, 3, 1, 1)
        self.lat_dm_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lat_dm_horizontalLayout.setObjectName("lat_dm_horizontalLayout")
        self.gridLayout_2.addLayout(self.lat_dm_horizontalLayout, 4, 3, 1, 1)
        self.copyClipboard_pushButton_2 = QtWidgets.QPushButton(CoordinateConverterDialog)
        self.copyClipboard_pushButton_2.setText("")
        self.copyClipboard_pushButton_2.setObjectName("copyClipboard_pushButton_2")
        self.gridLayout_2.addWidget(self.copyClipboard_pushButton_2, 4, 6, 2, 1)
        self.lat_d_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lat_d_horizontalLayout.setObjectName("lat_d_horizontalLayout")
        self.gridLayout_2.addLayout(self.lat_d_horizontalLayout, 1, 3, 1, 1)
        self.lon_d_horizontalLayout = QtWidgets.QHBoxLayout()
        self.lon_d_horizontalLayout.setObjectName("lon_d_horizontalLayout")
        self.gridLayout_2.addLayout(self.lon_d_horizontalLayout, 2, 3, 1, 1)
        self.copyClipboard_pushButton = QtWidgets.QPushButton(CoordinateConverterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyClipboard_pushButton.sizePolicy().hasHeightForWidth())
        self.copyClipboard_pushButton.setSizePolicy(sizePolicy)
        self.copyClipboard_pushButton.setText("")
        self.copyClipboard_pushButton.setObjectName("copyClipboard_pushButton")
        self.gridLayout_2.addWidget(self.copyClipboard_pushButton, 1, 6, 2, 1)
        self.degreeminutesecond_label = QtWidgets.QLabel(CoordinateConverterDialog)
        self.degreeminutesecond_label.setAlignment(QtCore.Qt.AlignCenter)
        self.degreeminutesecond_label.setObjectName("degreeminutesecond_label")
        self.gridLayout_2.addWidget(self.degreeminutesecond_label, 6, 1, 1, 5)
        self.degreeminute_label = QtWidgets.QLabel(CoordinateConverterDialog)
        self.degreeminute_label.setAlignment(QtCore.Qt.AlignCenter)
        self.degreeminute_label.setObjectName("degreeminute_label")
        self.gridLayout_2.addWidget(self.degreeminute_label, 3, 1, 1, 5)
        self.degree_label = QtWidgets.QLabel(CoordinateConverterDialog)
        self.degree_label.setAlignment(QtCore.Qt.AlignCenter)
        self.degree_label.setObjectName("degree_label")
        self.gridLayout_2.addWidget(self.degree_label, 0, 1, 1, 5)

        self.retranslateUi(CoordinateConverterDialog)
        QtCore.QMetaObject.connectSlotsByName(CoordinateConverterDialog)

    def retranslateUi(self, CoordinateConverterDialog):
        _translate = QtCore.QCoreApplication.translate
        CoordinateConverterDialog.setWindowTitle(_translate("CoordinateConverterDialog", "Dialog"))
        self.latitudeLabel_dms.setText(_translate("CoordinateConverterDialog", "Latitude:"))
        self.longitudelabel_dms.setText(_translate("CoordinateConverterDialog", "Longitude:"))
        self.latitudeLabel_dm.setText(_translate("CoordinateConverterDialog", "Latitude:"))
        self.longitudelabel_dm.setText(_translate("CoordinateConverterDialog", "Longitude:"))
        self.latitudelabel_d.setText(_translate("CoordinateConverterDialog", "Latitude:"))
        self.convert_pushButton.setText(_translate("CoordinateConverterDialog", "Convert"))
        self.longitudeLabel_d.setText(_translate("CoordinateConverterDialog", "Longitude:"))
        self.degreeminutesecond_label.setText(_translate("CoordinateConverterDialog", "DDDºMM\'SS.SSS\'\'"))
        self.degreeminute_label.setText(_translate("CoordinateConverterDialog", "DDDºMM.MM\'"))
        self.degree_label.setText(_translate("CoordinateConverterDialog", "DDD.DDDDº"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CoordinateConverterDialog = QtWidgets.QDialog()
    ui = Ui_CoordinateConverterDialog()
    ui.setupUi(CoordinateConverterDialog)
    CoordinateConverterDialog.show()
    sys.exit(app.exec_())

