# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gps_connection.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gpsConnectionWidget(object):
    def setupUi(self, gpsConnectionWidget):
        gpsConnectionWidget.setObjectName("gpsConnectionWidget")
        gpsConnectionWidget.resize(303, 233)
        gpsConnectionWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(gpsConnectionWidget)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gpsconnection_groupBox = QtWidgets.QGroupBox(gpsConnectionWidget)
        self.gpsconnection_groupBox.setMinimumSize(QtCore.QSize(285, 215))
        self.gpsconnection_groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid silver;\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    padding: 0px 5px 0px 5px;\n"
"}")
        self.gpsconnection_groupBox.setObjectName("gpsconnection_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gpsconnection_groupBox)
        self.verticalLayout.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serialPortRadioButton = QtWidgets.QRadioButton(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialPortRadioButton.sizePolicy().hasHeightForWidth())
        self.serialPortRadioButton.setSizePolicy(sizePolicy)
        self.serialPortRadioButton.setCheckable(True)
        self.serialPortRadioButton.setChecked(True)
        self.serialPortRadioButton.setObjectName("serialPortRadioButton")
        self.verticalLayout.addWidget(self.serialPortRadioButton)
        self.horizontal_layout_device = QtWidgets.QHBoxLayout()
        self.horizontal_layout_device.setObjectName("horizontal_layout_device")
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_device.addItem(spacerItem)
        self.deviceLabel = QtWidgets.QLabel(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceLabel.sizePolicy().hasHeightForWidth())
        self.deviceLabel.setSizePolicy(sizePolicy)
        self.deviceLabel.setObjectName("deviceLabel")
        self.horizontal_layout_device.addWidget(self.deviceLabel)
        self.deviceComboBox = QtWidgets.QComboBox(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceComboBox.sizePolicy().hasHeightForWidth())
        self.deviceComboBox.setSizePolicy(sizePolicy)
        self.deviceComboBox.setMinimumSize(QtCore.QSize(131, 0))
        self.deviceComboBox.setObjectName("deviceComboBox")
        self.horizontal_layout_device.addWidget(self.deviceComboBox)
        self.updateDevicesButton = QtWidgets.QPushButton(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateDevicesButton.sizePolicy().hasHeightForWidth())
        self.updateDevicesButton.setSizePolicy(sizePolicy)
        self.updateDevicesButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateDevicesButton.setIcon(icon)
        self.updateDevicesButton.setObjectName("updateDevicesButton")
        self.horizontal_layout_device.addWidget(self.updateDevicesButton)
        self.verticalLayout.addLayout(self.horizontal_layout_device)
        self.horizontal_layout_baud_rate = QtWidgets.QHBoxLayout()
        self.horizontal_layout_baud_rate.setObjectName("horizontal_layout_baud_rate")
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_baud_rate.addItem(spacerItem1)
        self.baudRateLabel = QtWidgets.QLabel(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudRateLabel.sizePolicy().hasHeightForWidth())
        self.baudRateLabel.setSizePolicy(sizePolicy)
        self.baudRateLabel.setObjectName("baudRateLabel")
        self.horizontal_layout_baud_rate.addWidget(self.baudRateLabel)
        self.baudRateComboBox = QtWidgets.QComboBox(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudRateComboBox.sizePolicy().hasHeightForWidth())
        self.baudRateComboBox.setSizePolicy(sizePolicy)
        self.baudRateComboBox.setObjectName("baudRateComboBox")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.baudRateComboBox.addItem("")
        self.horizontal_layout_baud_rate.addWidget(self.baudRateComboBox)
        self.verticalLayout.addLayout(self.horizontal_layout_baud_rate)
        self.TCPRadioButton = QtWidgets.QRadioButton(self.gpsconnection_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TCPRadioButton.sizePolicy().hasHeightForWidth())
        self.TCPRadioButton.setSizePolicy(sizePolicy)
        self.TCPRadioButton.setObjectName("TCPRadioButton")
        self.verticalLayout.addWidget(self.TCPRadioButton)
        self.tcpip_verticalLayout = QtWidgets.QVBoxLayout()
        self.tcpip_verticalLayout.setObjectName("tcpip_verticalLayout")
        self.horizontal_layout_ip = QtWidgets.QHBoxLayout()
        self.horizontal_layout_ip.setObjectName("horizontal_layout_ip")
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_ip.addItem(spacerItem2)
        self.ipLabel = QtWidgets.QLabel(self.gpsconnection_groupBox)
        self.ipLabel.setObjectName("ipLabel")
        self.horizontal_layout_ip.addWidget(self.ipLabel)
        self.ip_text = QtWidgets.QLineEdit(self.gpsconnection_groupBox)
        self.ip_text.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_text.sizePolicy().hasHeightForWidth())
        self.ip_text.setSizePolicy(sizePolicy)
        self.ip_text.setObjectName("ip_text")
        self.horizontal_layout_ip.addWidget(self.ip_text)
        self.tcpip_verticalLayout.addLayout(self.horizontal_layout_ip)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gga_portLabel = QtWidgets.QLabel(self.gpsconnection_groupBox)
        self.gga_portLabel.setObjectName("gga_portLabel")
        self.horizontalLayout_2.addWidget(self.gga_portLabel)
        self.gga_port_text = QtWidgets.QLineEdit(self.gpsconnection_groupBox)
        self.gga_port_text.setEnabled(False)
        self.gga_port_text.setMaximumSize(QtCore.QSize(55, 16777215))
        self.gga_port_text.setObjectName("gga_port_text")
        self.horizontalLayout_2.addWidget(self.gga_port_text)
        self.hdt_portLabel = QtWidgets.QLabel(self.gpsconnection_groupBox)
        self.hdt_portLabel.setObjectName("hdt_portLabel")
        self.horizontalLayout_2.addWidget(self.hdt_portLabel)
        self.hdt_port_text = QtWidgets.QLineEdit(self.gpsconnection_groupBox)
        self.hdt_port_text.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hdt_port_text.sizePolicy().hasHeightForWidth())
        self.hdt_port_text.setSizePolicy(sizePolicy)
        self.hdt_port_text.setMaximumSize(QtCore.QSize(55, 16777215))
        self.hdt_port_text.setObjectName("hdt_port_text")
        self.horizontalLayout_2.addWidget(self.hdt_port_text)
        self.tcpip_verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.tcpip_verticalLayout)
        self.verticalLayout_2.addWidget(self.gpsconnection_groupBox)
        self.ipLabel.setBuddy(self.ip_text)
        self.hdt_portLabel.setBuddy(self.hdt_port_text)

        self.retranslateUi(gpsConnectionWidget)
        QtCore.QMetaObject.connectSlotsByName(gpsConnectionWidget)

    def retranslateUi(self, gpsConnectionWidget):
        _translate = QtCore.QCoreApplication.translate
        gpsConnectionWidget.setWindowTitle(_translate("gpsConnectionWidget", "GPS Connection"))
        self.gpsconnection_groupBox.setTitle(_translate("gpsConnectionWidget", "GPS Connection"))
        self.serialPortRadioButton.setText(_translate("gpsConnectionWidget", "Serial Port"))
        self.deviceLabel.setText(_translate("gpsConnectionWidget", "Device:"))
        self.updateDevicesButton.setToolTip(_translate("gpsConnectionWidget", "Update device list"))
        self.baudRateLabel.setText(_translate("gpsConnectionWidget", "Baud rate:"))
        self.baudRateComboBox.setItemText(0, _translate("gpsConnectionWidget", "1200"))
        self.baudRateComboBox.setItemText(1, _translate("gpsConnectionWidget", "2400"))
        self.baudRateComboBox.setItemText(2, _translate("gpsConnectionWidget", "4800"))
        self.baudRateComboBox.setItemText(3, _translate("gpsConnectionWidget", "9600"))
        self.baudRateComboBox.setItemText(4, _translate("gpsConnectionWidget", "14400"))
        self.baudRateComboBox.setItemText(5, _translate("gpsConnectionWidget", "19200"))
        self.baudRateComboBox.setItemText(6, _translate("gpsConnectionWidget", "28800"))
        self.baudRateComboBox.setItemText(7, _translate("gpsConnectionWidget", "38400"))
        self.baudRateComboBox.setItemText(8, _translate("gpsConnectionWidget", "56000"))
        self.baudRateComboBox.setItemText(9, _translate("gpsConnectionWidget", "57600"))
        self.baudRateComboBox.setItemText(10, _translate("gpsConnectionWidget", "115200"))
        self.TCPRadioButton.setText(_translate("gpsConnectionWidget", "TCP/IP Connection"))
        self.ipLabel.setText(_translate("gpsConnectionWidget", "IP:"))
        self.gga_portLabel.setText(_translate("gpsConnectionWidget", "GGA Port:"))
        self.hdt_portLabel.setText(_translate("gpsConnectionWidget", "HDT Port:"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gpsConnectionWidget = QtWidgets.QWidget()
    ui = Ui_gpsConnectionWidget()
    ui.setupUi(gpsConnectionWidget)
    gpsConnectionWidget.show()
    sys.exit(app.exec_())

