# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_go_to_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GoToDialog(object):
    def setupUi(self, GoToDialog):
        GoToDialog.setObjectName("GoToDialog")
        GoToDialog.resize(376, 214)
        self.gridLayout = QtWidgets.QGridLayout(GoToDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_pushButton = QtWidgets.QPushButton(GoToDialog)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout.addWidget(self.cancel_pushButton)
        self.Ok_pushButton = QtWidgets.QPushButton(GoToDialog)
        self.Ok_pushButton.setObjectName("Ok_pushButton")
        self.horizontalLayout.addWidget(self.Ok_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.altitudeModeLabel = QtWidgets.QLabel(GoToDialog)
        self.altitudeModeLabel.setObjectName("altitudeModeLabel")
        self.gridLayout_2.addWidget(self.altitudeModeLabel, 2, 4, 1, 1)
        self.getCoordinatesButton = QtWidgets.QPushButton(GoToDialog)
        self.getCoordinatesButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.getCoordinatesButton.setText("")
        self.getCoordinatesButton.setObjectName("getCoordinatesButton")
        self.gridLayout_2.addWidget(self.getCoordinatesButton, 0, 6, 2, 1)
        self.z_tolerance_doubleSpinBox = QtWidgets.QDoubleSpinBox(GoToDialog)
        self.z_tolerance_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.z_tolerance_doubleSpinBox.setMinimum(0.0)
        self.z_tolerance_doubleSpinBox.setSingleStep(0.5)
        self.z_tolerance_doubleSpinBox.setProperty("value", 1.0)
        self.z_tolerance_doubleSpinBox.setObjectName("z_tolerance_doubleSpinBox")
        self.gridLayout_2.addWidget(self.z_tolerance_doubleSpinBox, 4, 6, 1, 1)
        self.x_label = QtWidgets.QLabel(GoToDialog)
        self.x_label.setObjectName("x_label")
        self.gridLayout_2.addWidget(self.x_label, 4, 1, 1, 1)
        self.altitudeModeCheckBox = QtWidgets.QCheckBox(GoToDialog)
        self.altitudeModeCheckBox.setObjectName("altitudeModeCheckBox")
        self.gridLayout_2.addWidget(self.altitudeModeCheckBox, 2, 6, 1, 1)
        self.altitudeLabel = QtWidgets.QLabel(GoToDialog)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.gridLayout_2.addWidget(self.altitudeLabel, 2, 0, 1, 1)
        self.surgeLabel = QtWidgets.QLabel(GoToDialog)
        self.surgeLabel.setObjectName("surgeLabel")
        self.gridLayout_2.addWidget(self.surgeLabel, 3, 0, 1, 1)
        self.longitudeLabel = QtWidgets.QLabel(GoToDialog)
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.gridLayout_2.addWidget(self.longitudeLabel, 1, 0, 1, 1)
        self.latitudeLabel = QtWidgets.QLabel(GoToDialog)
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.gridLayout_2.addWidget(self.latitudeLabel, 0, 0, 1, 1)
        self.latitudeLineEdit = QtWidgets.QLineEdit(GoToDialog)
        self.latitudeLineEdit.setObjectName("latitudeLineEdit")
        self.gridLayout_2.addWidget(self.latitudeLineEdit, 0, 1, 1, 5)
        self.tolerance_label = QtWidgets.QLabel(GoToDialog)
        self.tolerance_label.setObjectName("tolerance_label")
        self.gridLayout_2.addWidget(self.tolerance_label, 4, 0, 1, 1)
        self.y_label = QtWidgets.QLabel(GoToDialog)
        self.y_label.setObjectName("y_label")
        self.gridLayout_2.addWidget(self.y_label, 4, 3, 1, 1)
        self.x_tolerance_doubleSpinBox = QtWidgets.QDoubleSpinBox(GoToDialog)
        self.x_tolerance_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.x_tolerance_doubleSpinBox.setMinimum(0.0)
        self.x_tolerance_doubleSpinBox.setSingleStep(0.5)
        self.x_tolerance_doubleSpinBox.setProperty("value", 2.0)
        self.x_tolerance_doubleSpinBox.setObjectName("x_tolerance_doubleSpinBox")
        self.gridLayout_2.addWidget(self.x_tolerance_doubleSpinBox, 4, 2, 1, 1)
        self.y_tolerance_doubleSpinBox = QtWidgets.QDoubleSpinBox(GoToDialog)
        self.y_tolerance_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.y_tolerance_doubleSpinBox.setMinimum(0.0)
        self.y_tolerance_doubleSpinBox.setSingleStep(0.5)
        self.y_tolerance_doubleSpinBox.setProperty("value", 2.0)
        self.y_tolerance_doubleSpinBox.setObjectName("y_tolerance_doubleSpinBox")
        self.gridLayout_2.addWidget(self.y_tolerance_doubleSpinBox, 4, 4, 1, 1)
        self.surgeLineEdit = QtWidgets.QLineEdit(GoToDialog)
        self.surgeLineEdit.setObjectName("surgeLineEdit")
        self.gridLayout_2.addWidget(self.surgeLineEdit, 3, 1, 1, 6)
        self.longitudeLineEdit = QtWidgets.QLineEdit(GoToDialog)
        self.longitudeLineEdit.setObjectName("longitudeLineEdit")
        self.gridLayout_2.addWidget(self.longitudeLineEdit, 1, 1, 1, 5)
        self.zLineEdit = QtWidgets.QLineEdit(GoToDialog)
        self.zLineEdit.setObjectName("zLineEdit")
        self.gridLayout_2.addWidget(self.zLineEdit, 2, 1, 1, 3)
        self.z_label = QtWidgets.QLabel(GoToDialog)
        self.z_label.setObjectName("z_label")
        self.gridLayout_2.addWidget(self.z_label, 4, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(GoToDialog)
        QtCore.QMetaObject.connectSlotsByName(GoToDialog)

    def retranslateUi(self, GoToDialog):
        _translate = QtCore.QCoreApplication.translate
        GoToDialog.setWindowTitle(_translate("GoToDialog", "Go To"))
        self.cancel_pushButton.setText(_translate("GoToDialog", "Cancel"))
        self.Ok_pushButton.setText(_translate("GoToDialog", "Ok"))
        self.altitudeModeLabel.setText(_translate("GoToDialog", "Altitude:"))
        self.x_label.setText(_translate("GoToDialog", "X:"))
        self.altitudeLabel.setText(_translate("GoToDialog", "Z:"))
        self.surgeLabel.setText(_translate("GoToDialog", "Surge:"))
        self.longitudeLabel.setText(_translate("GoToDialog", "Longitude:"))
        self.latitudeLabel.setText(_translate("GoToDialog", "Latitude:"))
        self.latitudeLineEdit.setText(_translate("GoToDialog", "0.0"))
        self.tolerance_label.setText(_translate("GoToDialog", "Tolerance:"))
        self.y_label.setText(_translate("GoToDialog", "Y:"))
        self.surgeLineEdit.setText(_translate("GoToDialog", "0.5"))
        self.longitudeLineEdit.setText(_translate("GoToDialog", "0.0"))
        self.zLineEdit.setText(_translate("GoToDialog", "0.0"))
        self.z_label.setText(_translate("GoToDialog", "Z:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GoToDialog = QtWidgets.QDialog()
    ui = Ui_GoToDialog()
    ui.setupUi(GoToDialog)
    GoToDialog.show()
    sys.exit(app.exec_())

