# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_options.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(695, 178)
        self.gridLayout = QtWidgets.QGridLayout(OptionsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.auv_config_label = QtWidgets.QLabel(OptionsDialog)
        self.auv_config_label.setObjectName("auv_config_label")
        self.gridLayout.addWidget(self.auv_config_label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.auv_config_lineEdit = QtWidgets.QLineEdit(OptionsDialog)
        self.auv_config_lineEdit.setObjectName("auv_config_lineEdit")
        self.horizontalLayout_2.addWidget(self.auv_config_lineEdit)
        self.auv_config_pushButton = QtWidgets.QPushButton(OptionsDialog)
        self.auv_config_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.auv_config_pushButton.setObjectName("auv_config_pushButton")
        self.horizontalLayout_2.addWidget(self.auv_config_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_rm_lineEdit = QtWidgets.QLineEdit(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_rm_lineEdit.sizePolicy().hasHeightForWidth())
        self.user_rm_lineEdit.setSizePolicy(sizePolicy)
        self.user_rm_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.user_rm_lineEdit.setText("")
        self.user_rm_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_rm_lineEdit.setObjectName("user_rm_lineEdit")
        self.horizontalLayout_3.addWidget(self.user_rm_lineEdit)
        self.ip_rm_label = QtWidgets.QLabel(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_rm_label.sizePolicy().hasHeightForWidth())
        self.ip_rm_label.setSizePolicy(sizePolicy)
        self.ip_rm_label.setObjectName("ip_rm_label")
        self.horizontalLayout_3.addWidget(self.ip_rm_label)
        self.path_rm_lineEdit = QtWidgets.QLineEdit(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_rm_lineEdit.sizePolicy().hasHeightForWidth())
        self.path_rm_lineEdit.setSizePolicy(sizePolicy)
        self.path_rm_lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.path_rm_lineEdit.setObjectName("path_rm_lineEdit")
        self.horizontalLayout_3.addWidget(self.path_rm_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.coordinate_comboBox = QtWidgets.QComboBox(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinate_comboBox.sizePolicy().hasHeightForWidth())
        self.coordinate_comboBox.setSizePolicy(sizePolicy)
        self.coordinate_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.coordinate_comboBox.setObjectName("coordinate_comboBox")
        self.coordinate_comboBox.addItem("")
        self.coordinate_comboBox.addItem("")
        self.coordinate_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.coordinate_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.auto_canvasmarker_radioButton = QtWidgets.QRadioButton(OptionsDialog)
        self.auto_canvasmarker_radioButton.setObjectName("auto_canvasmarker_radioButton")
        self.horizontalLayout_4.addWidget(self.auto_canvasmarker_radioButton)
        self.manual_canvasmarker_radioButton = QtWidgets.QRadioButton(OptionsDialog)
        self.manual_canvasmarker_radioButton.setObjectName("manual_canvasmarker_radioButton")
        self.horizontalLayout_4.addWidget(self.manual_canvasmarker_radioButton)
        self.label_zoom = QtWidgets.QLabel(OptionsDialog)
        self.label_zoom.setEnabled(False)
        self.label_zoom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_zoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_zoom.setObjectName("label_zoom")
        self.horizontalLayout_4.addWidget(self.label_zoom)
        self.changingscale_spinBox = QtWidgets.QSpinBox(OptionsDialog)
        self.changingscale_spinBox.setEnabled(False)
        self.changingscale_spinBox.setMaximum(1000000)
        self.changingscale_spinBox.setProperty("value", 400)
        self.changingscale_spinBox.setObjectName("changingscale_spinBox")
        self.horizontalLayout_4.addWidget(self.changingscale_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 4, 1)
        self.coordinate_label = QtWidgets.QLabel(OptionsDialog)
        self.coordinate_label.setObjectName("coordinate_label")
        self.gridLayout.addWidget(self.coordinate_label, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(OptionsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.vessel_canvas_marker_mode_label = QtWidgets.QLabel(OptionsDialog)
        self.vessel_canvas_marker_mode_label.setObjectName("vessel_canvas_marker_mode_label")
        self.gridLayout.addWidget(self.vessel_canvas_marker_mode_label, 3, 0, 1, 1)

        self.retranslateUi(OptionsDialog)
        self.buttonBox.rejected.connect(OptionsDialog.reject)
        self.manual_canvasmarker_radioButton.toggled['bool'].connect(self.changingscale_spinBox.setEnabled)
        self.manual_canvasmarker_radioButton.toggled['bool'].connect(self.label_zoom.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Dialog"))
        self.auv_config_label.setText(_translate("OptionsDialog", "AUV configuration xml:"))
        self.auv_config_pushButton.setText(_translate("OptionsDialog", "..."))
        self.ip_rm_label.setText(_translate("OptionsDialog", "@ip:"))
        self.coordinate_comboBox.setItemText(0, _translate("OptionsDialog", "Degree"))
        self.coordinate_comboBox.setItemText(1, _translate("OptionsDialog", "Degree Minute"))
        self.coordinate_comboBox.setItemText(2, _translate("OptionsDialog", "Degree Minute Second"))
        self.auto_canvasmarker_radioButton.setText(_translate("OptionsDialog", "Auto"))
        self.manual_canvasmarker_radioButton.setText(_translate("OptionsDialog", "Manual"))
        self.label_zoom.setText(_translate("OptionsDialog", "Changing scale 1:"))
        self.coordinate_label.setText(_translate("OptionsDialog", "Coordinate Display:"))
        self.label.setText(_translate("OptionsDialog", "Remote Missions:"))
        self.vessel_canvas_marker_mode_label.setText(_translate("OptionsDialog", "Vessel Canvas Marker Mode:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsDialog = QtWidgets.QDialog()
    ui = Ui_OptionsDialog()
    ui.setupUi(OptionsDialog)
    OptionsDialog.show()
    sys.exit(app.exec_())

