# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_usbl.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_USBLWidget(object):
    def setupUi(self, USBLWidget):
        USBLWidget.setObjectName("USBLWidget")
        USBLWidget.resize(335, 583)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(USBLWidget.sizePolicy().hasHeightForWidth())
        USBLWidget.setSizePolicy(sizePolicy)
        USBLWidget.setMinimumSize(QtCore.QSize(240, 0))
        USBLWidget.setMaximumSize(QtCore.QSize(16000, 16000))
        self.verticalLayout = QtWidgets.QVBoxLayout(USBLWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(USBLWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 315, 563))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connectButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMaximumSize(QtCore.QSize(295, 16777215))
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout_2.addWidget(self.connectButton)
        self.trackwidget_usbl = TrackWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackwidget_usbl.sizePolicy().hasHeightForWidth())
        self.trackwidget_usbl.setSizePolicy(sizePolicy)
        self.trackwidget_usbl.setMinimumSize(QtCore.QSize(295, 110))
        self.trackwidget_usbl.setObjectName("trackwidget_usbl")
        self.verticalLayout_2.addWidget(self.trackwidget_usbl)
        self.trackwidget_gps = TrackWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackwidget_gps.sizePolicy().hasHeightForWidth())
        self.trackwidget_gps.setSizePolicy(sizePolicy)
        self.trackwidget_gps.setMinimumSize(QtCore.QSize(295, 110))
        self.trackwidget_gps.setObjectName("trackwidget_gps")
        self.verticalLayout_2.addWidget(self.trackwidget_gps)
        self.trackwidget_auv = TrackWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackwidget_auv.sizePolicy().hasHeightForWidth())
        self.trackwidget_auv.setSizePolicy(sizePolicy)
        self.trackwidget_auv.setMinimumSize(QtCore.QSize(295, 110))
        self.trackwidget_auv.setObjectName("trackwidget_auv")
        self.verticalLayout_2.addWidget(self.trackwidget_auv)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.position_auv_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.position_auv_label.setFont(font)
        self.position_auv_label.setObjectName("position_auv_label")
        self.horizontalLayout_5.addWidget(self.position_auv_label)
        self.auv_position_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auv_position_label.sizePolicy().hasHeightForWidth())
        self.auv_position_label.setSizePolicy(sizePolicy)
        self.auv_position_label.setMinimumSize(QtCore.QSize(150, 0))
        self.auv_position_label.setText("")
        self.auv_position_label.setObjectName("auv_position_label")
        self.horizontalLayout_5.addWidget(self.auv_position_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.depth_auv_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.depth_auv_label.setFont(font)
        self.depth_auv_label.setObjectName("depth_auv_label")
        self.horizontalLayout_6.addWidget(self.depth_auv_label)
        self.auv_depth_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auv_depth_label.sizePolicy().hasHeightForWidth())
        self.auv_depth_label.setSizePolicy(sizePolicy)
        self.auv_depth_label.setMinimumSize(QtCore.QSize(160, 0))
        self.auv_depth_label.setText("")
        self.auv_depth_label.setObjectName("auv_depth_label")
        self.horizontalLayout_6.addWidget(self.auv_depth_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.depth_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.depth_label.setFont(font)
        self.depth_label.setObjectName("depth_label")
        self.horizontalLayout_3.addWidget(self.depth_label)
        self.usbl_depth_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usbl_depth_label.sizePolicy().hasHeightForWidth())
        self.usbl_depth_label.setSizePolicy(sizePolicy)
        self.usbl_depth_label.setMinimumSize(QtCore.QSize(220, 0))
        self.usbl_depth_label.setText("")
        self.usbl_depth_label.setObjectName("usbl_depth_label")
        self.horizontalLayout_3.addWidget(self.usbl_depth_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.position_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.position_label.setFont(font)
        self.position_label.setObjectName("position_label")
        self.horizontalLayout_2.addWidget(self.position_label)
        self.usbl_position_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usbl_position_label.sizePolicy().hasHeightForWidth())
        self.usbl_position_label.setSizePolicy(sizePolicy)
        self.usbl_position_label.setMinimumSize(QtCore.QSize(220, 0))
        self.usbl_position_label.setText("")
        self.usbl_position_label.setObjectName("usbl_position_label")
        self.horizontalLayout_2.addWidget(self.usbl_position_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.status_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout.addWidget(self.status_label)
        self.usbl_status_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usbl_status_label.sizePolicy().hasHeightForWidth())
        self.usbl_status_label.setSizePolicy(sizePolicy)
        self.usbl_status_label.setMinimumSize(QtCore.QSize(240, 0))
        self.usbl_status_label.setText("")
        self.usbl_status_label.setObjectName("usbl_status_label")
        self.horizontalLayout.addWidget(self.usbl_status_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lastping_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lastping_label.setFont(font)
        self.lastping_label.setObjectName("lastping_label")
        self.horizontalLayout_4.addWidget(self.lastping_label)
        self.usbl_lastping_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usbl_lastping_label.sizePolicy().hasHeightForWidth())
        self.usbl_lastping_label.setSizePolicy(sizePolicy)
        self.usbl_lastping_label.setMinimumSize(QtCore.QSize(220, 0))
        self.usbl_lastping_label.setText("")
        self.usbl_lastping_label.setObjectName("usbl_lastping_label")
        self.horizontalLayout_4.addWidget(self.usbl_lastping_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.connectButton.raise_()
        self.connectButton.raise_()
        self.connectButton.raise_()
        self.connectButton.raise_()
        self.connectButton.raise_()
        self.trackwidget_auv.raise_()
        self.trackwidget_gps.raise_()
        self.trackwidget_usbl.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(USBLWidget)
        QtCore.QMetaObject.connectSlotsByName(USBLWidget)

    def retranslateUi(self, USBLWidget):
        _translate = QtCore.QCoreApplication.translate
        USBLWidget.setWindowTitle(_translate("USBLWidget", "USBL"))
        self.connectButton.setText(_translate("USBLWidget", "Connect"))
        self.position_auv_label.setText(_translate("USBLWidget", "Position (from AUV):"))
        self.depth_auv_label.setText(_translate("USBLWidget", "Depth (from AUV):"))
        self.depth_label.setText(_translate("USBLWidget", "Depth:"))
        self.position_label.setText(_translate("USBLWidget", "Position:"))
        self.status_label.setText(_translate("USBLWidget", "Status:"))
        self.lastping_label.setText(_translate("USBLWidget", "Last ping:"))

from canvastracks.trackwidget import TrackWidget
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    USBLWidget = QtWidgets.QWidget()
    ui = Ui_USBLWidget()
    ui.setupUi(USBLWidget)
    USBLWidget.show()
    sys.exit(app.exec_())

