# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_vesselpossystem.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VesselPosSystem(object):
    def setupUi(self, VesselPosSystem):
        VesselPosSystem.setObjectName("VesselPosSystem")
        VesselPosSystem.resize(620, 543)
        self.gridLayout = QtWidgets.QGridLayout(VesselPosSystem)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(VesselPosSystem)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 17, 0, 1, 4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_graphicsView = QtWidgets.QGraphicsView(VesselPosSystem)
        self.top_graphicsView.setObjectName("top_graphicsView")
        self.verticalLayout_2.addWidget(self.top_graphicsView)
        self.side_graphicsView = QtWidgets.QGraphicsView(VesselPosSystem)
        self.side_graphicsView.setObjectName("side_graphicsView")
        self.verticalLayout_2.addWidget(self.side_graphicsView)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 12, 1)
        self.vrp_gridLayout = QtWidgets.QGridLayout()
        self.vrp_gridLayout.setObjectName("vrp_gridLayout")
        self.vrp_x_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.vrp_x_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.vrp_x_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.vrp_x_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.vrp_x_offset_doubleSpinBox.setMinimum(-99.0)
        self.vrp_x_offset_doubleSpinBox.setSingleStep(1.0)
        self.vrp_x_offset_doubleSpinBox.setObjectName("vrp_x_offset_doubleSpinBox")
        self.vrp_gridLayout.addWidget(self.vrp_x_offset_doubleSpinBox, 0, 2, 1, 1)
        self.vrp_x_label = QtWidgets.QLabel(VesselPosSystem)
        self.vrp_x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vrp_x_label.setObjectName("vrp_x_label")
        self.vrp_gridLayout.addWidget(self.vrp_x_label, 0, 1, 1, 1)
        self.vrp_label = QtWidgets.QLabel(VesselPosSystem)
        self.vrp_label.setObjectName("vrp_label")
        self.vrp_gridLayout.addWidget(self.vrp_label, 0, 0, 1, 1)
        self.vrp_y_label = QtWidgets.QLabel(VesselPosSystem)
        self.vrp_y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vrp_y_label.setObjectName("vrp_y_label")
        self.vrp_gridLayout.addWidget(self.vrp_y_label, 1, 1, 1, 1)
        self.vrp_y_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.vrp_y_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.vrp_y_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.vrp_y_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.vrp_y_offset_doubleSpinBox.setMinimum(-99.0)
        self.vrp_y_offset_doubleSpinBox.setObjectName("vrp_y_offset_doubleSpinBox")
        self.vrp_gridLayout.addWidget(self.vrp_y_offset_doubleSpinBox, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.vrp_gridLayout, 3, 1, 1, 3)
        self.usbl_gridLayout = QtWidgets.QGridLayout()
        self.usbl_gridLayout.setObjectName("usbl_gridLayout")
        self.usbl_label = QtWidgets.QLabel(VesselPosSystem)
        self.usbl_label.setObjectName("usbl_label")
        self.usbl_gridLayout.addWidget(self.usbl_label, 0, 0, 1, 1)
        self.usbl_y_label = QtWidgets.QLabel(VesselPosSystem)
        self.usbl_y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usbl_y_label.setObjectName("usbl_y_label")
        self.usbl_gridLayout.addWidget(self.usbl_y_label, 1, 1, 1, 1)
        self.usbl_y_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.usbl_y_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.usbl_y_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.usbl_y_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.usbl_y_offset_doubleSpinBox.setMinimum(-99.0)
        self.usbl_y_offset_doubleSpinBox.setObjectName("usbl_y_offset_doubleSpinBox")
        self.usbl_gridLayout.addWidget(self.usbl_y_offset_doubleSpinBox, 1, 2, 1, 1)
        self.usbl_z_label = QtWidgets.QLabel(VesselPosSystem)
        self.usbl_z_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usbl_z_label.setObjectName("usbl_z_label")
        self.usbl_gridLayout.addWidget(self.usbl_z_label, 2, 1, 1, 1)
        self.usbl_x_label = QtWidgets.QLabel(VesselPosSystem)
        self.usbl_x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usbl_x_label.setObjectName("usbl_x_label")
        self.usbl_gridLayout.addWidget(self.usbl_x_label, 0, 1, 1, 1)
        self.usbl_x_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.usbl_x_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.usbl_x_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.usbl_x_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.usbl_x_offset_doubleSpinBox.setMinimum(-99.0)
        self.usbl_x_offset_doubleSpinBox.setObjectName("usbl_x_offset_doubleSpinBox")
        self.usbl_gridLayout.addWidget(self.usbl_x_offset_doubleSpinBox, 0, 2, 1, 1)
        self.usbl_z_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.usbl_z_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.usbl_z_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.usbl_z_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.usbl_z_offset_doubleSpinBox.setObjectName("usbl_z_offset_doubleSpinBox")
        self.usbl_gridLayout.addWidget(self.usbl_z_offset_doubleSpinBox, 2, 2, 1, 1)
        self.usbl_heading_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.usbl_heading_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.usbl_heading_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.usbl_heading_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.usbl_heading_doubleSpinBox.setMinimum(-180.0)
        self.usbl_heading_doubleSpinBox.setMaximum(180.0)
        self.usbl_heading_doubleSpinBox.setSingleStep(5.0)
        self.usbl_heading_doubleSpinBox.setObjectName("usbl_heading_doubleSpinBox")
        self.usbl_gridLayout.addWidget(self.usbl_heading_doubleSpinBox, 3, 2, 1, 1)
        self.usbl_label_degree = QtWidgets.QLabel(VesselPosSystem)
        self.usbl_label_degree.setObjectName("usbl_label_degree")
        self.usbl_gridLayout.addWidget(self.usbl_label_degree, 3, 0, 1, 1)
        self.usbl_heading_label = QtWidgets.QLabel(VesselPosSystem)
        self.usbl_heading_label.setObjectName("usbl_heading_label")
        self.usbl_gridLayout.addWidget(self.usbl_heading_label, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.usbl_gridLayout, 10, 1, 1, 3)
        self.gps_gridLayout = QtWidgets.QGridLayout()
        self.gps_gridLayout.setObjectName("gps_gridLayout")
        self.gps_label_degree = QtWidgets.QLabel(VesselPosSystem)
        self.gps_label_degree.setObjectName("gps_label_degree")
        self.gps_gridLayout.addWidget(self.gps_label_degree, 2, 0, 1, 1)
        self.gps_heading_label = QtWidgets.QLabel(VesselPosSystem)
        self.gps_heading_label.setObjectName("gps_heading_label")
        self.gps_gridLayout.addWidget(self.gps_heading_label, 2, 1, 1, 1)
        self.gps_x_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.gps_x_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.gps_x_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.gps_x_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.gps_x_offset_doubleSpinBox.setMinimum(-99.0)
        self.gps_x_offset_doubleSpinBox.setObjectName("gps_x_offset_doubleSpinBox")
        self.gps_gridLayout.addWidget(self.gps_x_offset_doubleSpinBox, 0, 2, 1, 1)
        self.gps_x_label = QtWidgets.QLabel(VesselPosSystem)
        self.gps_x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gps_x_label.setObjectName("gps_x_label")
        self.gps_gridLayout.addWidget(self.gps_x_label, 0, 1, 1, 1)
        self.gps_label = QtWidgets.QLabel(VesselPosSystem)
        self.gps_label.setObjectName("gps_label")
        self.gps_gridLayout.addWidget(self.gps_label, 0, 0, 1, 1)
        self.gps_y_label = QtWidgets.QLabel(VesselPosSystem)
        self.gps_y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gps_y_label.setObjectName("gps_y_label")
        self.gps_gridLayout.addWidget(self.gps_y_label, 1, 1, 1, 1)
        self.gps_heading_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.gps_heading_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.gps_heading_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.gps_heading_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.gps_heading_doubleSpinBox.setMinimum(-180.0)
        self.gps_heading_doubleSpinBox.setMaximum(180.0)
        self.gps_heading_doubleSpinBox.setSingleStep(5.0)
        self.gps_heading_doubleSpinBox.setObjectName("gps_heading_doubleSpinBox")
        self.gps_gridLayout.addWidget(self.gps_heading_doubleSpinBox, 2, 2, 1, 1)
        self.gps_y_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.gps_y_offset_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.gps_y_offset_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.gps_y_offset_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.gps_y_offset_doubleSpinBox.setMinimum(-99.0)
        self.gps_y_offset_doubleSpinBox.setObjectName("gps_y_offset_doubleSpinBox")
        self.gps_gridLayout.addWidget(self.gps_y_offset_doubleSpinBox, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gps_gridLayout, 6, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 2, 1, 1)
        self.size_gridLayout = QtWidgets.QGridLayout()
        self.size_gridLayout.setObjectName("size_gridLayout")
        self.vessel_width_label = QtWidgets.QLabel(VesselPosSystem)
        self.vessel_width_label.setObjectName("vessel_width_label")
        self.size_gridLayout.addWidget(self.vessel_width_label, 1, 0, 1, 1)
        self.vessel_width_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.vessel_width_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.vessel_width_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.vessel_width_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.vessel_width_doubleSpinBox.setMaximum(1000.0)
        self.vessel_width_doubleSpinBox.setObjectName("vessel_width_doubleSpinBox")
        self.size_gridLayout.addWidget(self.vessel_width_doubleSpinBox, 1, 1, 1, 1)
        self.vessel_lengthlabel = QtWidgets.QLabel(VesselPosSystem)
        self.vessel_lengthlabel.setObjectName("vessel_lengthlabel")
        self.size_gridLayout.addWidget(self.vessel_lengthlabel, 0, 0, 1, 1)
        self.vessel_length_doubleSpinBox = QtWidgets.QDoubleSpinBox(VesselPosSystem)
        self.vessel_length_doubleSpinBox.setMinimumSize(QtCore.QSize(82, 26))
        self.vessel_length_doubleSpinBox.setMaximumSize(QtCore.QSize(82, 26))
        self.vessel_length_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.vessel_length_doubleSpinBox.setMaximum(1000.0)
        self.vessel_length_doubleSpinBox.setObjectName("vessel_length_doubleSpinBox")
        self.size_gridLayout.addWidget(self.vessel_length_doubleSpinBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.size_gridLayout, 2, 1, 1, 3)

        self.retranslateUi(VesselPosSystem)
        self.buttonBox.accepted.connect(VesselPosSystem.accept)
        self.buttonBox.rejected.connect(VesselPosSystem.reject)
        QtCore.QMetaObject.connectSlotsByName(VesselPosSystem)

    def retranslateUi(self, VesselPosSystem):
        _translate = QtCore.QCoreApplication.translate
        VesselPosSystem.setWindowTitle(_translate("VesselPosSystem", "Dialog"))
        self.vrp_x_label.setText(_translate("VesselPosSystem", "X:"))
        self.vrp_label.setText(_translate("VesselPosSystem", "VRP offset (m)"))
        self.vrp_y_label.setText(_translate("VesselPosSystem", "Y:"))
        self.usbl_label.setText(_translate("VesselPosSystem", "USBL offset (m)"))
        self.usbl_y_label.setText(_translate("VesselPosSystem", "Y:"))
        self.usbl_z_label.setText(_translate("VesselPosSystem", "Z:"))
        self.usbl_x_label.setText(_translate("VesselPosSystem", "X:"))
        self.usbl_label_degree.setText(_translate("VesselPosSystem", "USBL offset (º)"))
        self.usbl_heading_label.setText(_translate("VesselPosSystem", "Heading:"))
        self.gps_label_degree.setText(_translate("VesselPosSystem", "GPS offset (º)"))
        self.gps_heading_label.setText(_translate("VesselPosSystem", "Heading:"))
        self.gps_x_label.setText(_translate("VesselPosSystem", "X:"))
        self.gps_label.setText(_translate("VesselPosSystem", "GPS offset (m)"))
        self.gps_y_label.setText(_translate("VesselPosSystem", "Y:"))
        self.vessel_width_label.setText(_translate("VesselPosSystem", "Vessel width (m):"))
        self.vessel_lengthlabel.setText(_translate("VesselPosSystem", "Vessel length (m):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VesselPosSystem = QtWidgets.QDialog()
    ui = Ui_VesselPosSystem()
    ui.setupUi(VesselPosSystem)
    VesselPosSystem.show()
    sys.exit(app.exec_())

