# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_waypoint_edit.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WaypointEditWidget(object):
    def setupUi(self, WaypointEditWidget):
        WaypointEditWidget.setObjectName("WaypointEditWidget")
        WaypointEditWidget.resize(320, 492)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WaypointEditWidget.sizePolicy().hasHeightForWidth())
        WaypointEditWidget.setSizePolicy(sizePolicy)
        WaypointEditWidget.setMinimumSize(QtCore.QSize(320, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(WaypointEditWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(WaypointEditWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 300, 472))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.previousWpButtonLayout = QtWidgets.QHBoxLayout()
        self.previousWpButtonLayout.setObjectName("previousWpButtonLayout")
        self.previousWpButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.previousWpButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.previousWpButton.setObjectName("previousWpButton")
        self.previousWpButtonLayout.addWidget(self.previousWpButton)
        self.titleLayout.addLayout(self.previousWpButtonLayout)
        self.TitleWaypointLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleWaypointLabel.sizePolicy().hasHeightForWidth())
        self.TitleWaypointLabel.setSizePolicy(sizePolicy)
        self.TitleWaypointLabel.setTextFormat(QtCore.Qt.AutoText)
        self.TitleWaypointLabel.setScaledContents(False)
        self.TitleWaypointLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleWaypointLabel.setWordWrap(False)
        self.TitleWaypointLabel.setObjectName("TitleWaypointLabel")
        self.titleLayout.addWidget(self.TitleWaypointLabel)
        self.nextWpButtonLayout = QtWidgets.QHBoxLayout()
        self.nextWpButtonLayout.setObjectName("nextWpButtonLayout")
        self.nextWpButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.nextWpButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextWpButton.sizePolicy().hasHeightForWidth())
        self.nextWpButton.setSizePolicy(sizePolicy)
        self.nextWpButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.nextWpButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nextWpButton.setAutoFillBackground(False)
        self.nextWpButton.setObjectName("nextWpButton")
        self.nextWpButtonLayout.addWidget(self.nextWpButton)
        self.titleLayout.addLayout(self.nextWpButtonLayout)
        self.verticalLayout_3.addLayout(self.titleLayout)
        self.LatitudeLayout_5 = QtWidgets.QHBoxLayout()
        self.LatitudeLayout_5.setObjectName("LatitudeLayout_5")
        self.latitude_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latitude_label.sizePolicy().hasHeightForWidth())
        self.latitude_label.setSizePolicy(sizePolicy)
        self.latitude_label.setObjectName("latitude_label")
        self.LatitudeLayout_5.addWidget(self.latitude_label)
        self.latitude_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latitude_lineEdit.sizePolicy().hasHeightForWidth())
        self.latitude_lineEdit.setSizePolicy(sizePolicy)
        self.latitude_lineEdit.setObjectName("latitude_lineEdit")
        self.LatitudeLayout_5.addWidget(self.latitude_lineEdit)
        self.verticalLayout_3.addLayout(self.LatitudeLayout_5)
        self.LongitudeLayout_5 = QtWidgets.QHBoxLayout()
        self.LongitudeLayout_5.setObjectName("LongitudeLayout_5")
        self.longitude_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longitude_label.sizePolicy().hasHeightForWidth())
        self.longitude_label.setSizePolicy(sizePolicy)
        self.longitude_label.setObjectName("longitude_label")
        self.LongitudeLayout_5.addWidget(self.longitude_label)
        self.longitude_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.longitude_lineEdit.setObjectName("longitude_lineEdit")
        self.LongitudeLayout_5.addWidget(self.longitude_lineEdit)
        self.verticalLayout_3.addLayout(self.LongitudeLayout_5)
        self.ZAltitudeHLayout_5 = QtWidgets.QHBoxLayout()
        self.ZAltitudeHLayout_5.setObjectName("ZAltitudeHLayout_5")
        self.z_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.z_label.setObjectName("z_label")
        self.ZAltitudeHLayout_5.addWidget(self.z_label)
        self.z_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.z_lineEdit.setObjectName("z_lineEdit")
        self.ZAltitudeHLayout_5.addWidget(self.z_lineEdit)
        self.altitude_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.altitude_label.setObjectName("altitude_label")
        self.ZAltitudeHLayout_5.addWidget(self.altitude_label)
        self.altitude_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.altitude_checkBox.setText("")
        self.altitude_checkBox.setObjectName("altitude_checkBox")
        self.ZAltitudeHLayout_5.addWidget(self.altitude_checkBox)
        self.verticalLayout_3.addLayout(self.ZAltitudeHLayout_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.controller_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.controller_label.setObjectName("controller_label")
        self.horizontalLayout_5.addWidget(self.controller_label)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.ParkTimeHLayout_5 = QtWidgets.QHBoxLayout()
        self.ParkTimeHLayout_5.setObjectName("ParkTimeHLayout_5")
        self.parkTime_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.parkTime_label.setObjectName("parkTime_label")
        self.ParkTimeHLayout_5.addWidget(self.parkTime_label)
        self.parkTime_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.parkTime_lineEdit.setEnabled(True)
        self.parkTime_lineEdit.setObjectName("parkTime_lineEdit")
        self.ParkTimeHLayout_5.addWidget(self.parkTime_lineEdit)
        self.verticalLayout_3.addLayout(self.ParkTimeHLayout_5)
        self.SpeedHLayout_5 = QtWidgets.QHBoxLayout()
        self.SpeedHLayout_5.setObjectName("SpeedHLayout_5")
        self.speedLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.speedLabel.setObjectName("speedLabel")
        self.SpeedHLayout_5.addWidget(self.speedLabel)
        self.speedlineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.speedlineEdit.setObjectName("speedlineEdit")
        self.SpeedHLayout_5.addWidget(self.speedlineEdit)
        self.verticalLayout_3.addLayout(self.SpeedHLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tolerance_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tolerance_label.setObjectName("tolerance_label")
        self.verticalLayout_2.addWidget(self.tolerance_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tolerance_x_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tolerance_x_label.setObjectName("tolerance_x_label")
        self.horizontalLayout_2.addWidget(self.tolerance_x_label)
        self.tolerance_x_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.tolerance_x_lineEdit.setMaximumSize(QtCore.QSize(69, 16777215))
        self.tolerance_x_lineEdit.setObjectName("tolerance_x_lineEdit")
        self.horizontalLayout_2.addWidget(self.tolerance_x_lineEdit)
        self.tolerance_y_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tolerance_y_label.setObjectName("tolerance_y_label")
        self.horizontalLayout_2.addWidget(self.tolerance_y_label)
        self.tolerance_y_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.tolerance_y_lineEdit.setMaximumSize(QtCore.QSize(74, 16777215))
        self.tolerance_y_lineEdit.setObjectName("tolerance_y_lineEdit")
        self.horizontalLayout_2.addWidget(self.tolerance_y_lineEdit)
        self.tolerance_z_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tolerance_z_label.setObjectName("tolerance_z_label")
        self.horizontalLayout_2.addWidget(self.tolerance_z_label)
        self.tolerance_z_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.tolerance_z_lineEdit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.tolerance_z_lineEdit.setObjectName("tolerance_z_lineEdit")
        self.horizontalLayout_2.addWidget(self.tolerance_z_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridActionCallLayout_8 = QtWidgets.QGridLayout()
        self.gridActionCallLayout_8.setObjectName("gridActionCallLayout_8")
        self.listWidget_3 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridActionCallLayout_8.addWidget(self.listWidget_3, 1, 0, 1, 3)
        self.removeAction_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeAction_pushButton.sizePolicy().hasHeightForWidth())
        self.removeAction_pushButton.setSizePolicy(sizePolicy)
        self.removeAction_pushButton.setObjectName("removeAction_pushButton")
        self.gridActionCallLayout_8.addWidget(self.removeAction_pushButton, 0, 2, 1, 1)
        self.addAction_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.addAction_pushButton.setObjectName("addAction_pushButton")
        self.gridActionCallLayout_8.addWidget(self.addAction_pushButton, 0, 1, 1, 1)
        self.actions_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.actions_label.setObjectName("actions_label")
        self.gridActionCallLayout_8.addWidget(self.actions_label, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridActionCallLayout_8)
        self.delete_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.verticalLayout_3.addWidget(self.delete_pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(WaypointEditWidget)
        QtCore.QMetaObject.connectSlotsByName(WaypointEditWidget)

    def retranslateUi(self, WaypointEditWidget):
        _translate = QtCore.QCoreApplication.translate
        WaypointEditWidget.setWindowTitle(_translate("WaypointEditWidget", "Form"))
        self.previousWpButton.setText(_translate("WaypointEditWidget", "<-"))
        self.TitleWaypointLabel.setText(_translate("WaypointEditWidget", "No waypoints"))
        self.nextWpButton.setText(_translate("WaypointEditWidget", "->"))
        self.latitude_label.setText(_translate("WaypointEditWidget", "Latitude:   "))
        self.latitude_lineEdit.setText(_translate("WaypointEditWidget", "0.0"))
        self.longitude_label.setText(_translate("WaypointEditWidget", "Longitude:"))
        self.longitude_lineEdit.setText(_translate("WaypointEditWidget", "0.0"))
        self.z_label.setText(_translate("WaypointEditWidget", "Z: "))
        self.z_lineEdit.setText(_translate("WaypointEditWidget", "0.0"))
        self.altitude_label.setText(_translate("WaypointEditWidget", "Altitude Mode: "))
        self.controller_label.setText(_translate("WaypointEditWidget", "Controller: "))
        self.comboBox.setProperty("currentText", _translate("WaypointEditWidget", "waypoint"))
        self.comboBox.setItemText(0, _translate("WaypointEditWidget", "waypoint"))
        self.comboBox.setItemText(1, _translate("WaypointEditWidget", "section"))
        self.comboBox.setItemText(2, _translate("WaypointEditWidget", "park"))
        self.parkTime_label.setText(_translate("WaypointEditWidget", "Park Time: "))
        self.parkTime_lineEdit.setText(_translate("WaypointEditWidget", "10.0"))
        self.speedLabel.setText(_translate("WaypointEditWidget", "Speed: "))
        self.speedlineEdit.setText(_translate("WaypointEditWidget", "0.0"))
        self.tolerance_label.setText(_translate("WaypointEditWidget", "Tolerance:"))
        self.tolerance_x_label.setText(_translate("WaypointEditWidget", "X:"))
        self.tolerance_x_lineEdit.setText(_translate("WaypointEditWidget", "2.0"))
        self.tolerance_y_label.setText(_translate("WaypointEditWidget", "Y:"))
        self.tolerance_y_lineEdit.setText(_translate("WaypointEditWidget", "2.0"))
        self.tolerance_z_label.setText(_translate("WaypointEditWidget", "Z:"))
        self.tolerance_z_lineEdit.setText(_translate("WaypointEditWidget", "1.0"))
        self.removeAction_pushButton.setText(_translate("WaypointEditWidget", "-"))
        self.addAction_pushButton.setText(_translate("WaypointEditWidget", "+"))
        self.actions_label.setText(_translate("WaypointEditWidget", "Actions to call"))
        self.delete_pushButton.setText(_translate("WaypointEditWidget", "Delete Waypoint"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaypointEditWidget = QtWidgets.QWidget()
    ui = Ui_WaypointEditWidget()
    ui.setupUi(WaypointEditWidget)
    WaypointEditWidget.show()
    sys.exit(app.exec_())

